### ISSUE TITLE
Wrong output in timeZoneFormatted when time zone offset is negative

### ISSUE THREAD

**Issue by wkolov** [sadespresso/moment_dart#10]
If hous is negative, the output looks like "--5:00" instead of "-05:00"

![image](https://user-images.githubusercontent.com/37083408/223344272-12bdf0c2-e630-464a-8c83-39baffb23a7c.png)

**Comment by sadespresso** [comment]
Thank you for pointing out!

[Release 0.17.2](https://pub.dev/packages/moment_dart) with the fix should be live now :))
