### ISSUE TITLE
startOf(DurationUnit.week) and endOf(DurationUnit.week) errors

### ISSUE THREAD

**Issue by libwiki** [sadespresso/moment_dart#13]
### startOf(DurationUnit.week) and endOf(DurationUnit.week) errors

* moment_dart: ^1.0.1

<img width="1217" alt="image" src="https://github.com/sadespresso/moment_dart/assets/30712221/f7953c13-75a2-4b72-a359-d3b5a7886a77">

**Comment by sadespresso** [comment]
Thank you for reporting the issue.

`Moment.startOf(DurationUnit.week)` should return `startOfLocalWeek`

Same story for endOf

I will be pushing a fix very soon

**Comment by sadespresso** [comment]
It's fixed in [1.1.0](https://pub.dartlang.org/packages/moment_dart)

`Moment.startOf(DurationUnit.week)` uses `Moment.defaultLocalization.weekStart`
