### ISSUE TITLE
.endOf(DurationUnit.week) returns wrong value for Saturday

### ISSUE THREAD

**Issue by alexnix** [sadespresso/moment_dart#19]
The default convention seems to be that week starts on Sunday and ends on Saturday.

In this context, if I call `.endOf(DurationUnit.week)` for a date, which is Saturday, I should get back the same day. What happens is, I get the next Saturday. 

`endOfLocalWeek(7)` also gives me the next Saturday, when called with a Saturday date.

**Comment by sadespresso** [comment]
Hello there!

You are right, thank you for reporting.

Fix can be expected soon
