### ISSUE TITLE
[Enhancement] Global localization

### ISSUE THREAD

**Issue by stevenosse** [sadespresso/moment_dart#3]
Hello,
Thanks for this package, it's great!

It would be nice to be able to define a location globally. A syntax like 

`Moment.setGlobalLocalization(Locale());`

Thank you.

**Comment by sadespresso** [comment]
This is now available for use in version [0.15.0](https://pub.dev/packages/moment_dart/versions/0.15.0)

Thank you!

**Comment by stevenosse** [comment]
> This is now available for use in version [0.15.0](https://pub.dev/packages/moment_dart/versions/0.15.0)
> 
> Thank you!

Already using it!
