### ISSUE TITLE
0 hours in en_US localization

### ISSUE THREAD

**Issue by tigrenok00** [sadespresso/moment_dart#9]
Hi!

When using the default en_US localization, the noon time is displayed like this: Today at **0:08 PM.** From customers input, I understand that the american way is to display it as **12:08 PM** - not zero. 
The format tokens section example on the main page actually shows no zero:
h    1 2 ... 11 12
Is current behavior correct? How to achieve this using default localization?
Thanks!
Maria

**Comment by sadespresso** [comment]
Hello!

I can confirm that the current behavior results in **0:08PM**. This is not the correct behavior.

I will soon publish a release with fix for this issue.

Thank you! How did I miss this 😅

**Comment by sadespresso** [comment]
Hello @tigrenok00,

[moment_dart@0.17.1](https://pub.dev/packages/moment_dart) is now live on [pub.dev](https://pub.dev/). Please check it out ✨

**Comment by tigrenok00** [comment]
Looking good! Thank you for the fast response!
